name: fuse-fs test

on: [push]

jobs:

  code_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: run integration test
      run: |
        cd test
        chmod a+x integration_test.sh
        ./integration_test.sh
